# Basic
title: Condition Number
subtitle: A space saving all my reading and work
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: Hello World!
creator: <a href="https://github.com/guabao/">@Jiazhou Wang</a>

url: "https://github.com/guabao/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/guabao'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: https-guabao-github-io 
#    # duoshuo: 
    
# Social
social:
    #weibo: onevcat
    github: guabao
    #twitter: onevcat
    #gplus: 107108267983477358170
    mail: wjz270025872@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
